<template>
  <div>
    <AseTable
      :rows="rows"
      :columns="columns"
      row-key="email"
      emptyLabel="No administrators found"
      :rows-per-page-options="[0]"
      :hide-bottom="rows?.length > 0"
      style="max-height: calc(100vh - 200px); min-height: 400px"
      :isLoading="companyAdmin.loading"
      :loadMore="loadMore"
      @onLoadMore="handleLoadMore"
    >
      <template v-slot:body-cell="props">
        <q-td :props="props" @click="getUserInfo(props.row)">
          {{ props.value }}
        </q-td>
      </template>
      <template v-slot:top-right>
        <div class="text-right">
          <q-fab
            color="primary"
            icon="download"
            label="Download"
            padding="sm"
            rounded
            :direction="isMobile ? 'right' : 'left'"
            :class="{ 'q-mt-sm': isMobile }"
          >
            <q-fab-action color="primary" icon="fas fa-file-pdf" push @click="downloadPDFReport()">
              <q-tooltip anchor="top middle" self="bottom middle">Download PDF</q-tooltip>
            </q-fab-action>
            <q-fab-action color="primary" icon="fas fa-file-csv" push @click="downloadCSVReport()">
              <q-tooltip anchor="top middle" self="bottom middle">Download CSV</q-tooltip>
            </q-fab-action>
          </q-fab>
        </div>
      </template>
    </AseTable>

    <div class="hidden" :class="{ 'bg-night-blue-important': $q.dark.isActive }">
      <section class="q-my-xl q-py-xl" ref="thepdf" :class="{ 'bg-night-blue-important': $q.dark.isActive }">
        <hr />
        <h3 class="ase-roboto text-center text-weight-medium">Administrators List</h3>
        <hr />
        <div class="row items-center justify-center" style="height: 50rem">
          <h6 class="text-center html2pdf__page-break">
            Report generated by {{ fetchUserInfo.firstName }} on
            <br />
            <span>{{ readableDateNow() }}</span>
          </h6>
        </div>
        <div class="q-pa-md">
          <AseTable
            :columns="columns"
            :rows="companyAdmin.adminUsers"
            row-key="index"
            :virtual-scroll="false"
            :rows-per-page-options="[0]"
          ></AseTable>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup>
import html2pdf from 'html2pdf.js'
import { downloadCSV, readableDateNow, urlSafeBase64Encode } from 'src/utils/reuseFunctions'

import { useLoginStore } from 'src/store/pinia/login'
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useQuasar } from 'quasar'
import { useScreenSize } from 'src/composables/useScreenSize'
import { useCompanyAdmin } from 'src/store/pinia/company/admin'

const columns = [
  { name: 'index', label: 'Number', field: 'index', sortable: true, align: 'left' },
  { name: 'fullName', label: 'Full Name', field: 'full_name', sortable: true, align: 'left' },
  { name: 'email', label: 'Email', field: 'email', sortable: true, align: 'left' }
]

const companyAdmin = useCompanyAdmin()
const { isMobile } = useScreenSize()
const loginStore = useLoginStore()

const router = useRouter()
const $q = useQuasar()

const thepdf = ref(null)
const fetchUserInfo = computed(() => {
  return loginStore.fetchUserInfo
})

const filename = computed(() => {
  return `Administrators List - ${readableDateNow()}`
})

const loadMore = computed(() => {
  return companyAdmin.payload.LastEvaluatedKey && !companyAdmin.loading
})

const rows = computed(() => {
  return companyAdmin.adminUsers.map((e, i) => {
    e.index = i + 1
    return e
  })
})

onMounted(() => {
  bootingAdmin()
})

function downloadPDFReport() {
  html2pdf(thepdf.value, {
    filename: filename.value,
    margin: [10, 0, 15, 0]
  })
}

function downloadCSVReport() {
  const status = downloadCSV(columns, companyAdmin.adminUsers, filename.value)

  if (!status) {
    $q.notify({
      message: 'Error while exporting',
      color: 'negative',
      position: 'top',
      timeout: 2000
    })
  }
}

function getUserInfo(row) {
  router.push(`/portal/company/profile-info/${urlSafeBase64Encode(row.email)}/${urlSafeBase64Encode(row.full_name)}`)
}

async function fetchCompanyAdmin() {
  await companyAdmin.fetchAdminUsers()
}

async function handleLoadMore() {
  fetchCompanyAdmin()
}

function bootingAdmin() {
  if (companyAdmin.adminUsers?.length) return
  fetchCompanyAdmin()
}
</script>

<style lang="sass">
.q-table th
  font-size: 14px
  font-weight: bolder

.q-table td
  cursor: pointer

.bg-night-blue-important
  background-color: #02032d !important
</style>
